---
install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - ruby --version
  - gem --version
  - bundle install
build: off
test_script:
  - bundle exec rake spec

environment:
  matrix:
    - ruby_version: "30-x64"
    - ruby_version: "27-x64"
    - ruby_version: "26-x64"
    - ruby_version: "25-x64"
